# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c0eed8c5ca1ab7a53977533de64e531c93ab7f52703a67a5b9f2c94e09f3f87b524c7993a8719161646fb59d48f25abe462cdca00f4ea7d93d985cf8ccf215

test:
  secret_key_base: 5f5b91d568acb91e91d4a509b4e569db5f649a373036bbc246c8fb98553c1c09d9c1061b4c3a52fb297bdfd27342595113d851b6f3ae1739eb62067a92e304df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
